name: Renovate
on:
  schedule:
    - cron: '0 6 * * *' # Run daily at 6 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          installation_id: ${{ secrets.RENOVATE_INSTALL_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f66d8679fcfcfa051abde6e7a623007173bf5164 # v46.1.12
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_USERNAME: "jcooter-renovate[bot]"
          RENOVATE_GIT_AUTHOR: "jcooter-renovate <3537147+jcooter-renovate[bot]@users.noreply.github.com>"
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL=debug
        with:
          config: .github/renovate.json5
          token: ${{ steps.get_token.outputs.token }}
